baseURL = 'https://l4l4dev.github.io/'
languageCode = 'en-us'
title = "Mika's Profile"
theme = 'toha'

# [languages]
#   [languages.en]
#     languageCode = "en"
#     languageName = "English"
#     title = "John's Blog"
#     weight = 1
#   [languages.bn]
#     languageCode = "bn"
#     languageName = "বাংলা"
#     title = "জনের ব্লগ"
#     weight = 2

# defaultContentLanguage = "en"

[markup]
[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]

enableEmoji = true

# [markup]
# [markup.goldmark.renderer]
# unsafe = true
# [markup.tableOfContents]
# startLevel = 2
# endLevel = 6
# ordered = false

# [outputs]
# home = ["HTML", "RSS", "JSON"]

# enableEmoji = true

[params]
# Background image of the landing page
background = "/images/site/DSC02380.JPG"

# [params.logo]
# main = "/images/site/main-logo.png"
# inverted = "/images/site/inverted-logo.png"
# favicon = "/images/site/favicon.png"

# gitRepo = "https://github.com/hugo-toha/hugo-toha.github.io"
# gitBranch = "main"

# [params.topNavbar]
# maxVisibleSections = 5

[params.features]
[params.features.analytics]
enabled = true
[params.features.analytics.services.google]
id = "G-6KVB7QTBW8"

# [params.features.theme]
# enable = true
# [params.features.theme.services]
# light = true
# dark = true
# default = "system"

# [params.features.portfolio]
# enable = true

# [params.features.blog]
# enable = true
# showAuthor = true
# [params.features.blog.shareButtons]
# facebook = true
# twitter = true
# linkedin = true
# reddit = true
# whatsapp = true
# email = true

# [params.features.notes]
# enable = true

# [params.features.comment]
# enable = false
# [params.features.comment.services.disqus]
# shortName = "toha-example-site"


# [params.features.support]
# enable = false
# [params.features.support.services.kofi]
# user = "hossainemruz"
# text = "Tip Me"
# textColor = "#f9fafc"
# backgroundColor = "#248aaa"

# [params.features.toc]
# enable = true

# [params.features.tags]
# enable = true
# on_card = true

# [params.features.flags]
# enable = true

# [params.features.embedpdf]
# enable = true

# [params.features.flowchart]
# enable = true
# [params.features.flowchart.services.mermaid]
# theme = "forest"

# [params.features.math]
# enable = true
# [params.features.math.services.katex]
# [[params.features.math.services.katex.delimiters]]
# left = "$$"
# right = "$$"
# display = true
# [[params.features.math.services.katex.delimiters]]
# left = "\\["
# right = "\\]"
# display = true
# [[params.features.math.services.katex.delimiters]]
# left = "$"
# right = "$"
# display = false
# [[params.features.math.services.katex.delimiters]]
# left = "\\("
# right = "\\)"
# display = false

# [params.features.syntaxHighlight]
# enable = true
# [params.features.syntaxHighlight.services.hljs]
# noHighlightRe = "/^no-highlight$/i"

# [params.features.videoPlayer]
# enable = true
# [params.features.videoPlayer.services.plyr]

# [params.features.readingTime]
# enable = false

# [params.features.pagination]
# maxPostsPerPage = 12

[params.footer]
enable = true
template = "footer.html"
[params.footer.navigation]
enable = true
customMenus = true
[params.footer.contactMe]
enable = true
[params.footer.credentials]
enable = false
[params.footer.newsletter]
enable = false
[params.footer.disclaimer]
enable = false


[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
disable = false
respectDoNotTrack = true
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = false


# Use Hugo modules to add theme
[module]
[[module.imports]]
path = "github.com/hugo-toha/toha/v4"
[[module.mounts]]
source = "static/files"
target = "static/files"
[[module.mounts]]
source = "./node_modules/flag-icon-css/flags"
target = "static/flags"
[[module.mounts]]
source = "./node_modules/@fontsource/mulish/files"
target = "static/files"
[[module.mounts]]
source = "./node_modules/katex/dist/fonts"
target = "static/fonts"
