baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'toha'

# Use Hugo modules to add theme
[module]
  [[module.imports]]
    path = "github.com/hugo-toha/toha/v4"
