baseURL = 'https://l4l4dev.github.io/'
languageCode = 'en-us'
title = "Mika's Profile"
theme = 'toha'

[params]
# Background image of the landing page
background = "/images/site/DSC02380.JPG"

# Use Hugo modules to add theme
[module]
[[module.imports]]
path = "github.com/hugo-toha/toha/v4"

[[module.mounts]]
source = "./node_modules/flag-icon-css/flags"
target = "static/flags"

[[module.mounts]]
source = "./node_modules/@fontsource/mulish/files"
target = "static/files"

[[module.mounts]]
source = "./node_modules/katex/dist/fonts"
target = "static/fonts"
